const fs=require('fs'),vm=require('vm'),assert=require('assert');
const script=fs.readFileSync('native/metadata_collector.js','utf8');
const uri='spotify:track:0000000000000000000001';
let requests=0,resolutions=0,getters=0;
const forbidden=()=>{requests++;throw Error('network forbidden');};
const state={item:{uri,metadata:{title:'Song',artist_name:'Artist',album_title:'Album',duration:'200000'}}};
const player={getState:()=>state,getEvents:()=>({})};
const query={queryKey:['cached-track',uri],state:{data:{release_date:'2026-09-30',genres:['Rock'],lyrics:{lines:[{words:'one'},{words:'two é'}]}}}};
const wrong={uri:'spotify:track:0000000000000000000002',metadata:{genre:'WRONG'}};
const registry={_map:new Map([[Symbol.for('PlayerAPI'),{instance:player}]]),resolve:()=>{resolutions++;throw Error('no service construction');}};
const value={registry,query,wrong};
Object.defineProperty(value,'dangerous',{enumerable:true,get(){getters++;forbidden();}});
const main={__reactContainer$test:{memoizedProps:{value}}};
const output=[];let elapsed=0;const clock={now:()=>performance.now()+elapsed};
const context={window:{__floggfyNative:true,CosmosAsync:{get:forbidden}},document:{querySelector:()=>main},console:{info:x=>output.push(x)},performance:clock,fetch:forbidden,XMLHttpRequest:forbidden,WebSocket:forbidden,setInterval:()=>{},encodeURIComponent};
vm.runInNewContext(script,context);
for(let i=0;i<20;i++)context.window.__floggfyPoll();
assert(output.some(x=>x.includes('DATE=2026-09-30')&&x.includes('GENRE=Rock')&&x.includes('LYRICS=one%0Atwo%20%C3%A9')));
assert(!output.some(x=>x.includes('WRONG')));
const currentMessages=()=>output.filter(x=>x.startsWith('FLOGGFY_PLAYBACK_V1:'));
assert(currentMessages().some(x=>x.includes('title=Song')));
const count=output.length;context.window.__floggfyPoll();assert.equal(output.length,count);
elapsed=16000;context.window.__floggfyPoll();assert.equal(output.length,count+2);
query.state.data.lyrics.lines.push({words:'cached update'});
context.window.__floggfyPoll();assert(output.at(-1).includes('cached%20update'));
state.item={uri:'spotify:track:0000000000000000000003',metadata:{title:'Other',artist_name:'Artist',album_title:'Album',duration:'100000'}};
context.window.__floggfyPoll();assert(currentMessages().at(-1).includes('title=Other'));assert(!output.at(-1).includes('DATE=')&&!output.at(-1).includes('LYRICS='));
state.item.metadata.year='2024';state.item.metadata.genre='Jazz';
context.window.__floggfyPoll();assert(output.at(-1).includes('YEAR=2024')&&output.at(-1).includes('GENRE=Jazz'));
const trap=o=>{Object.defineProperty(o,'month',{enumerable:true,get(){getters++;forbidden();}});return o;};
state.playbackQuality={bitrateLevel:'VERY_HIGH',targetBitrateLevel:'LOSSLESS'};
context.window.__floggfyPoll();assert(output.at(-1).includes('playback_quality=very_high'));
state.playbackQuality.bitrateLevel='LOSSLESS';context.window.__floggfyPoll();
assert(output.at(-1).includes('playback_quality=lossless'));
state.playbackQuality.bitrateLevel=99;context.window.__floggfyPoll();
assert(!output.at(-1).includes('playback_quality=')); // Unknown enum, never use target quality.
for(const [i,level] of ['low','normal','high','very_high','lossless','lossless_24'].entries()){
 state.playbackQuality.bitrateLevel=i+1;context.window.__floggfyPoll();
 assert(output.at(-1).includes('playback_quality='+level));
}
state.playbackQuality.bitrateLevel='HIFI24';context.window.__floggfyPoll();
assert(output.at(-1).includes('playback_quality=lossless_24'));
state.playbackQuality=undefined;state.playback_quality={bitrate_level:'HIGH'};
context.window.__floggfyPoll();assert(output.at(-1).includes('playback_quality=high'));
const qualityTrap={};Object.defineProperty(qualityTrap,'bitrate_level',{get(){getters++;forbidden();}});
state.playback_quality=qualityTrap;context.window.__floggfyPoll();
assert(!output.at(-1).includes('playback_quality='));
state.item.metadata.year=undefined;state.item.album={date:trap({year:2026})};
Object.defineProperty(state.item,'lyrics',{enumerable:true,get(){getters++;forbidden();}});
context.window.__floggfyPoll();assert(output.at(-1).includes('DATE=2026'));
const lyric={};Object.defineProperty(lyric,'lines',{enumerable:true,get(){getters++;forbidden();}});
const fresh={uri:'spotify:track:0000000000000000000004',metadata:{title:'Fresh',artist_name:'Artist',album_title:'Album',duration:'100000',lyrics:lyric}};
state.item=fresh;context.window.__floggfyPoll();assert(!output.at(-1).includes('LYRICS='));
fresh.metadata['artist_name:1']='Guest';
fresh.metadata['album_artist_name:1']='Guest';fresh.metadata.album_artist_name='Artist';
fresh.metadata.album_label='Example Records';fresh.metadata.publisher='Example Publishing';
fresh.metadata.album_track_count='0';
fresh.album={releaseDate:{isoString:'2024-05-06T00:00:00Z'}};
context.window.__floggfyPoll();
assert(output.at(-1).includes('ARTIST=Artist%3B%20Guest'));
assert(output.at(-1).includes('ALBUMARTIST=Artist%3B%20Guest'));
assert(output.at(-1).includes('DATE=2024-05-06'));
assert(output.at(-1).includes('LABEL=Example%20Records'));
assert(output.at(-1).includes('PUBLISHER=Example%20Publishing'));
assert(!output.at(-1).includes('TRACKTOTAL=0'));
fresh.metadata.year='2024';context.window.__floggfyPoll();
assert(output.at(-1).includes('DATE=2024-05-06')); // Do not replace a full date with a coarse year.
const indexed=[];Object.defineProperty(indexed,'0',{get(){getters++;forbidden();}});fresh.metadata.genres=indexed;
context.window.__floggfyPoll();
Object.defineProperty(state,'item',{get(){getters++;forbidden();},configurable:true});context.window.__floggfyPoll();
assert.equal(requests,0);assert.equal(resolutions,0);assert.equal(getters,0);
assert(!/https?:\/\/|AuthorizationAPI|\.resolve\(|\.fetchQuery\(/.test(script));
console.log('PASS: cached metadata, exact track association, cache updates, missing fields, zero requests/service resolutions/accessor reads');
